### ISSUE TITLE
No bundle ability 

### ISSUE THREAD

**Issue by moneydance** [littledivy/deno_swc#42]
👋  Hi it appears the bundle function was removed when the wasm migration was made https://github.com/nestdotland/deno_swc/pull/24/files#diff-e8c3622ccfbed67f4b3058cd4417bf41d066236f49c6f3e63b7c243b584c6734L4 is there anyway this functionality could be added back?

It seems the node version of this supports this feature https://github.com/swc-project/swc/blob/main/node-swc/src/index.ts#L296

**Comment by ayame113** [comment]
I noticed that I can use swc's bundle function by using https://github.com/denoland/deno_emit.

**Comment by littledivy** [comment]
yes, use https://github.com/denoland/deno_emit for bundle
